spring:
  datasource:
    url: jdbc:mariadb://ec2-13-125-167-23.ap-northeast-2.compute.amazonaws.com:3306/sku
    username: root
    password: A!CWUgeouv5evo
    driver-class-name: org.mariadb.jdbc.Driver

  kafka:
    bootstrap-servers:
      - 172.31.34.238:9092
      - 172.31.44.175:9092
      - 172.31.33.93:9092
    producer:
      acks: all

spring.data:
  redis:
    host: localhost         # Redis 서버 호스트
    port: 6379              # Redis 서버 포트