spring:
  datasource:
    url: jdbc:mariadb://${DB_IP}:3306/sku
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  kafka:
    bootstrap-servers:
      - ${BROKER_1}:9092
      - ${BROKER_2}:9092
      - ${BROKER_3}:9092
    producer:
      acks: all

spring.data:
  redis:
    host: localhost         # Redis 서버 호스트
    port: 6379              # Redis 서버 포트