spring:
  datasource:
    url: jdbc:mariadb://ec2-13-125-167-23.ap-northeast-2.compute.amazonaws.com:3306/sku
    username: root
    password: A!CWUgeouv5evo
    driver-class-name: org.mariadb.jdbc.Driver