spring:
  web:
    resources:
      static-locations: classpath:/templates/AdminLTE-3.2.0-rc/

  datasource:
    url: jdbc:mariadb://${DB_IP}:3306/sku
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      port: 6379
      host: ${REDIS_IP}

logging:
  level:
    org.hibernate.sql: debug


server:
  port: 8081


