version: "3"

services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=password123!
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    networks:
      fluentd_network:
        ipv4_address: 172.28.0.2 # db 서비스에 할당된 고정 IP

  app:
    image: matomo
    restart: always
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    networks:
      fluentd_network:
        ipv4_address: 172.28.0.3 # app 서비스에 할당된 고정 IP
    ports:
      - 8080:80

  nginx:
    image: nginx:1.18.0
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./container_niWx9Jy3.js:/etc/nginx/html/js/container_niWx9Jy3.js
      - ./container_9KD9SNRT.js:/etc/nginx/html/js/container_9KD9SNRT.js
      - ./container_VXDKU75K.js:/etc/nginx/html/js/container_VXDKU75K.js
      - ./matomo.js:/etc/nginx/html/matomo.js
    networks:
      fluentd_network:
        ipv4_address: 172.28.0.4 # nginx 서비스에 할당된 고정 IP
    ports:
      - "81:80"
    depends_on:
      - fluentd
      
  fluentd:
    build: .  # Dockerfile을 사용하도록 설정
    restart: always
    networks:
      fluentd_network:
        ipv4_address: 172.28.0.5 # fluentd 서비스에 할당된 고정 IP
    ports:
      - "9880:9880"
      - "9881:9881"
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf

volumes:
  db:
  matomo:

networks:
  fluentd_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
